name: pibiti
services:
    flask: # Flask + Tensorflow
        build: 
          context: .
          dockerfile: ./DOCKER/flask/dockerfile
        depends_on:
          - db
        ports:
        - '5000:5000'
        environment:
          - FLASK_ENV=production
          #USANDO MESMAS CREDENCIAIS DO DB!
          - MONGO_URI=mongodb://admin:Lf123456@db:27017/PARALISIA6_NERVO?authSource=admin #URLS INTERNAS PODEM USAR DNS DO COMPOSE!
          - CELERY_BROKER_URL=redis://localhost:6379/0
          - CELERY_RESULT_BACKEND=redis://localhost:6379/0
        networks:
          - projeto
        volumes:
          - flask:/FLASK
        restart: unless-stopped


    frontend: #Vue + Vite
        build: 
          context: .
          dockerfile: ./DOCKER/frontend/dockerfile
        depends_on:
          - flask
        ports:
        - '5173:5173'
        environment:
        # URL tem que ser de IP público externo ao docker ja que código do Vite vai rodar no browser
          VITE_BACKEND_URL: http://31.97.84.210:5000 #MUDAR PARA IP OU DOMÍNIO DA MÁQUINA RODANDO SERVIÇO
          NODE_ENV: development
        networks:
          - projeto
        volumes:
          - frontend:/frontend
        restart: unless-stopped


    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
          - "6379:6379"
        networks:
          - projeto
        restart: unless-stopped


    celery_worker:
      build: 
          context: .
          dockerfile: ./DOCKER/celery/dockerfile
      command: celery -A worker.tasks worker --loglevel=info
      volumes:
        - ./worker:/app/worker
      depends_on:
        - redis
      networks:
        - projeto
      restart: unless-stopped


    db: # MongoDB
      image: mongo@sha256:936020698d1b62b73f6bd40d52f172eb90e2a79e955aa4de26975100e5e991c6
      ports: [27017:27017]
      environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Lf123456
      volumes:
        - db:/data/db
      networks:
      - projeto
      restart: unless-stopped

networks:
  projeto:
    driver: bridge

volumes:
    db: 
    flask: 
    frontend: 
