name: SISTEMA_WEB_PIBITI
services:
    flask: # Flask + Tensorflow
        build: 
          context: .
          dockerfile: ./DOCKER/flask/dockerfile
        ports:
        - '5000:5000'
        environment:
          FLASK_ENV: development
        networks:
          - teste
        volumes:
          - flask:/FLASK
    frontend: #Vue + Vite
        build: 
          context: .
          dockerfile: ./DOCKER/frontend/dockerfile
        ports:
        - '5173:5173'
        environment:
          NODE_ENV: development
        networks:
          - teste
        volumes:
          - frontend:/frontend
    db: # MongoDB
      image: mongo@sha256:936020698d1b62b73f6bd40d52f172eb90e2a79e955aa4de26975100e5e991c6
      ports: [27017:27017]
      volumes:
          - db:/data/db
      networks:
        - teste
networks:
  teste:

volumes:
    db: 
    flask: 
    frontend: 
