# Use the official Node.js image from the Docker Hub
FROM node:18 as builder

# Set the working directory in the container
WORKDIR /frontend

COPY ./vite-project/package*.json ./
# Install the application dependencies
RUN npm install

# Copy the source code to the working directory
COPY ./vite-project ./


# Expose the port the application will run on
EXPOSE 5153

# Roda Servidor vite
# CMD ["npm", "run", "dev", "--","--host"]