# Use the official Node.js image from the Docker Hub
from node:18 as builder

# Set the working directory in the container
WORKDIR /frontend

# Copy package.json and package-lock.json to the working directory
COPY ./vite-project ./

# Install the application dependencies
RUN npm install

# Expose the port the application will run on
EXPOSE 5153

# Roda Servidor vite
CMD ["npm", "run", "dev", "--","--host"]