# python3.9-slim (debian-based)
FROM python:3.9-slim-bullseye AS builder

# Set environment variables to avoid user prompts during installation
ENV DEBIAN_FRONTEND=noninteractive
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /FLASK

# Install dependencies and clean up
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    ffmpeg \
    bash \
    gcc \
    libsm6 \
    libxext6 \
    libgl1-mesa-glx \
    #PARTE DO WEASYPRINT!
    python3-pip python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
# Copy requirements and install Python dependencies

RUN python3 -m venv /opt/venv  
ENV PATH="/opt/venv/bin:$PATH"

COPY FLASK/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY ./FLASK ./
COPY ./.env ./


FROM python:3.9-slim-bullseye AS runner_flask
# FROM python:3.9-slim AS runner_flask

WORKDIR /FLASK

# VOLUME ["/FLASK"]
# Copy the virtualenv from builder
COPY --from=builder /opt/venv /opt/venv  
ENV PATH="/opt/venv/bin:$PATH"
# Copy only necessary files from the builder stage
COPY --from=builder /FLASK /FLASK

# Reinstall only runtime libs (no gcc, no weasyprint build deps)
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1-mesa-glx \
    python3-pip python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Verify required files exist
RUN test -f ./permalink-googleDrive-pibiti6-nervo.json || (echo "permalink-googleDrive-pibiti6-nervo.json file not found in FLASK directory" && exit 1)
RUN test -f ./.env || (echo ".env file not found in FLASK directory" && exit 1)

# SO PRA TESTAR WEASYPRINT (retirar em producao)
# RUN weasyprint https://weasyprint.org /tmp/weasyprint-website.pdf

EXPOSE 5000
# CMD ["python", "-m", "server"] COMANDO ANTIGO PARA RODAR SERVIDOR DO FLASK
CMD ["gunicorn", "--bind", "--access-logfile", "-", "--error-logfile", "-", "--capture-output" , "-", "--log-level", "debug", "0.0.0.0:5000", "server:app"]
