name: Deploy to Local Linux VM

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile          # Explicitly specify Dockerfile location
        push: true
        tags: lfaoliveira/sistema_pibiti:latest

    - name: SSH to remote server and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PIBITI_HOST }}
        username: ${{ secrets.PIBITI_USER }}
        key: ${{ secrets.PIBITI_SSH_KEY }}
        script: |
          docker pull lfaoliveira/sistema_pibiti:latest
          docker-compose down
          docker-compose up -d --build
