name: Deploy to Local Linux VM

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH to remote server and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PIBITI_HOST }}
        username: ${{ secrets.PIBITI_USER }}
        key: ${{ secrets.PIBITI_SSH_KEY }}
        script: |
          cd ~/pibiti

          # Fetch the latest code
          git fetch origin
          git pull origin

          docker pull 
          docker compose down
          docker compose up -d --build
